---
apiVersion: v1
kind: Template
metadata:
  name: insights-runtimes-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: insights-runtimes-frontend
    spec:
      API:
        versions:
          - v1
      envName: ${ENV_NAME}
      title: Runtimes
      deploymentRepo: https://github.com/RedHatInsights/insights-runtimes-frontend
      frontend:
        paths:
          - /apps/insights-runtimes-frontend
      image: ${IMAGE}:${IMAGE_TAG}

      module:
        manifestLocation: '/apps/insights-runtimes-frontend/fed-mods.json'
        # modules:
        #   - id: 'overview'
        #     module: './RootApp'
        #     routes:
        #       - pathname: /staging/starter

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/insights-runtimes-frontend
